# -*- coding: utf-8 -*-
"""Text_mining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFN6VtDwkninXlQSoVKpa6wDgUczm4r9
"""

!pip install emoji

!pip install contractions

import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
import emoji
import contractions

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

def clean_data(data):
  if isinstance(data,str):
    data = contractions.fix(data)
    data = re.sub(r'[^a-zA-Z\s]','',data)
    data = data.lower().strip()
    tokens = word_tokenize(data)
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]

    cleaned_data = ' '.join(tokens)
    return cleaned_data

data = pd.read_csv("reviews_1.csv")
df = pd.DataFrame(data)
df.head()

df['text'] = df['text'].apply(clean_data)

df.to_csv('clensed_reviews.csv',index=False)